apiVersion: apps/v1
kind: Deployment
metadata:
  name: swe645p2-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: swe645p2
  template:
    metadata:
      labels:
        app: swe645p2
    spec:
      containers:
      - name: swe645p2
        image: swe645aspsr/assignment2swe645aspsr
        ports:
        - containerPort: 80
        imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: swe645p2-service
spec:
  ports:
  - port: 8014
    protocol: TCP
    targetPort: 8080
  selector:
    app: swe645p2
  type: LoadBalancer
